# Generated by Django 5.2.7 on 2025-10-15 15:52

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, default=core.models.generate_case_id, editable=False, help_text='Unique identifier for the dispute case', max_length=64, unique=True, verbose_name='Case ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('submitted', 'Submitted to Amazon'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', help_text='Current status of the dispute case', max_length=32, verbose_name='Case Status')),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_cases', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_cases', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_evidence/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.disputecase')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_return_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('return_reason', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition_on_return', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.order')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
        migrations.AddField(
            model_name='disputecase',
            name='linked_returns',
            field=models.ManyToManyField(blank=True, related_name='dispute_cases', to='core.return'),
        ),
    ]
