# Generated by Django 5.2.7 on 2025-10-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='amazon_return_id',
        ),
    ]
