# Generated by Django 5.2.7 on 2025-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_return_amazon_return_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputecase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', help_text='Current status of the dispute case', max_length=20, verbose_name='Case Status'),
        ),
    ]
