# Generated by Django 5.2.7 on 2025-10-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_disputecase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputecase',
            name='status',
        ),
    ]
